### ISSUE TITLE
Intraday perforance report when using 1 minute data?

### ISSUE THREAD

**Issue by kvak** [quantopian/zipline#2040]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
* Operating System: (Windows Version or `$ uname --all`)
`4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`* Python Version: `$ python --version`
`Python 3.5.2`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
`64`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
`pip`
* Python packages: `$ pip freeze` or `$ conda list`

```
alembic==0.9.6
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2017.11.5
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.1.2
empyrical==0.3.3
idna==2.6
intervaltree==2.1.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
multipledispatch==0.4.9
networkx==2.0
numexpr==2.6.4
numpy==1.13.3
pandas==0.18.1
pandas-datareader==0.5.0
patsy==0.4.1
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.15
statsmodels==0.8.0
tables==3.4.2
toolz==0.8.2
urllib3==1.22
zipline==1.1.1

```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
Intraday performance report
* What happened instead?
Daily performance report

Here is how you can reproduce this issue on your machine:

**Comment by imkoukou** [comment]
The problem is in algorithm.py, you can find the following main loop for all bars:
for perf in self.get_generator():
            perfs.append(perf)

            # convert perf dict to pandas dataframe
            daily_stats = self._create_daily_stats(perfs)
            self.analyze(daily_stats)

the daily_stats keeps all information for analyze() results parameter. Inside the self._create_daily_stats you can find results data is only recorded by every day.
[ My solution ]
Add a _create_minute_stats fuction to replace the  _create_daily_stats() function. 
You can only copy the _create_daily_stats function def, and replace all "daily" string to "minute". I tested, that works. 
Then in the loop "for perf in self.get_generator():" use the minute stats.
            minute_stats = self._create_minute_stats(perfs)
            self.analyze(minute_stats)

**Comment by apoorvkalra** [comment]
@imkoukou could you place an edited algorithm.py file here?
i tried replacing all the daily string to minute string and end up getting no performance data at all..

**Comment by imkoukou** [comment]
@apoorvkalra Hi. I updated the edited algorithm.py I am using and the original one. You can compare them to see what I changed.

The displayed report depends on what is returned by def run() function in algorithm.py.
I would like to return the daily report, cause volume of minute data report is too annoying.
It would be displayed like this....
![minute report](https://user-images.githubusercontent.com/9660349/41805951-be501e16-76ed-11e8-84ab-dff97b92bfc9.jpg)

[algorithm.zip](https://github.com/quantopian/zipline/files/2129648/algorithm.zip)

**Comment by studyquant** [comment]
it doesn't work in my zipline 1.2.0, python 3.5 .  since  the perf variable has no 
 'minute_perf' key. 

`    
        try:
            perfs = []
            self.get_generator()
            for perf in self.get_generator():
                perfs.append(perf)

            # convert perf dict to pandas dataframe


            daily_stats = self._create_daily_stats(perfs)
            if self.sim_params.data_frequency == 'daily':
                self.analyze(daily_stats)

            minute_stats = self._create_minute_stats(perfs)
            # Revised by studyquant
            if self.sim_params.data_frequency == 'minute':
                minute_stats = self._create_minute_stats(perfs)
                self.analyze(minute_stats)
        finally:
            self.data_portal = None
`

`
        for perf in perfs:
            if 'minute_perf' in perf:
                # print("perf is:\n",perf)
    
                perf['minute_perf'].update(
                    perf['minute_perf'].pop('recorded_vars')
                )
                perf['minute_perf'].update(perf['cumulative_risk_metrics'])

                daytime = perf['period_start'].strftime("%a")
                # Only analyze day is in the CustomBusinessDay of our calenday.
                if (daytime in workDayStrList):
                    minute_perfs.append(perf['minute_perf'])
            else:
                self.risk_report = perf

        minute_dts = pd.DatetimeIndex(
            [p['period_close'] for p in minute_perfs], tz='UTC'
        )
`

**Comment by imkoukou** [comment]
@studyquant 
1. Have you done the correct setting for minute csv data, including calendar setting? In the last version of Zipline, the minute data process have been included, which is much easier to configure for minute data simulation.
2. Did you run the script with minute data_frequency, and the specified start time and end time is within the csv data range

**Comment by studyquant** [comment]
Dear imkoukou:
  thank you for your reply. My data setting and calendar setting is current. And now I have updated the zipline into 1.3.0 version.

The panel like this:
`'
date                                                                      
2018-02-05 17:48:00  7170.000000  7171.000000  7170.000000  7170.990234   
2018-02-05 17:49:00  7131.990234  7171.000000  7170.990234  7131.990234   
2018-02-05 17:50:00  7120.000000  7137.359863  7132.000000  7120.020020   
2018-02-05 17:51:00  7113.000000  7121.000000  7120.040039  7113.000000   
2018-02-05 17:52:00  7113.000000  7122.000000  7113.000000  7121.990234   

                        volume  
date                            
2018-02-05 17:48:00   3.425961  
2018-02-05 17:49:00   5.209975  
2018-02-05 17:50:00  14.767619  
2018-02-05 17:51:00  18.237879  
2018-02-05 17:52:00  22.768671  
<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 72277 (major_axis) x 5 (minor_axis)
Items axis: BTC to BTC
Major_axis axis: 2018-02-05 17:48:00+00:00 to 2018-03-27 22:24:00+00:00
Minor_axis axis: low to volume`

in the zipline/ algorithm.py file, I have add a function in class
`    def _create_minute_stats(self, perfs):
        # create minute and cumulative stats dataframe
        minute_perfs = []
        workDayStrList = self.trading_calendar.day.weekmask.split(" ")
        # TODO: the loop here could overwrite expected properties
        # of minute_perf. Could potentially raise or log a
        # warning.
        # perfDF = pd.DataFrame(perfs)
        # print("daily stats perfs are:\n",perfDF.head(),"\n...\n",perfDF.tail())

        for perf in perfs:
            if 'minute_perf' in perf:
                # print("perf is:\n",perf)
    
                perf['minute_perf'].update(
                    perf['minute_perf'].pop('recorded_vars')
                )
                perf['minute_perf'].update(perf['cumulative_risk_metrics'])

                daytime = perf['period_start'].strftime("%a")
                # Only analyze day is in the CustomBusinessDay of our calenday.
                if (daytime in workDayStrList):
                    minute_perfs.append(perf['minute_perf'])
            else:
                self.risk_report = perf

        minute_dts = pd.DatetimeIndex(
            [p['period_close'] for p in minute_perfs], tz='UTC'
        )
       
        minute_stats = pd.DataFrame(minute_perfs, index=minute_dts)

        return minute_stats`

and revisde 
`        try:
            perfs = []
            for perf in self.get_generator():
                perfs.append(perf)

            # convert perf dict to pandas dataframe
            daily_stats = self._create_daily_stats(perfs)
            if self.sim_params.data_frequency == 'daily':
                self.analyze(daily_stats)

            ### Revised by me ###
            # user srcript analyze is executed here:
            # ### user file : analyze(context=None, results=None)
            if self.sim_params.data_frequency == 'minute':
                minute_stats = self._create_minute_stats(perfs)
                self.analyze(minute_stats)
        finally:
            self.data_portal = None

        # return None
        # return daily_stats shall display the daily report after simulation even if in minute frequency. 
        # return daily_stats
        # return minute_stats shall display the minute report after simulation, NA for daily frequency.
        return minute_stats
        `

it does not display introday report. 
since in _create_minute_stats(self, perfs) function:
`        for perf in perfs:
            if 'minute_perf' in perf:
                # print("perf is:\n",perf)
    
                perf['minute_perf'].update(
                    perf['minute_perf'].pop('recorded_vars')
                )
                perf['minute_perf'].update(perf['cumulative_risk_metrics'])

                daytime = perf['period_start'].strftime("%a")
                # Only analyze day is in the CustomBusinessDay of our calenday.
                if (daytime in workDayStrList):
                    minute_perfs.append(perf['minute_perf'])
            else:
                self.risk_report = perf`


`'minute_perf' in perf
Out[8]: 
False`

So, there is no minute_perf in perf varable.  while, the daily_perf  is in perf variable.
`'daily_perf' in perf
Out[11]: 
True`

due to  no minute_perf key in perf varable, the minute_stats is returned, it is a empty dataframe

`perf = zipline.run_algorithm(start=datetime(2018, 3, 8, 0, 0, 0, 0, pytz.utc),
                             end=datetime(2018, 3, 10, 0, 0, 0, 0, pytz.utc),
                             initialize=initialize,
                             trading_calendar=TwentyFourHR(),
                             capital_base=1000000,
                             handle_data=handle_data,
                             data_frequency='minute',
                             data=panel)
print(perf)
Empty DataFrame
Columns: []
Index: []`


I have download the files you uploaded,  replaced the algorithm file and run. it unable to run, 
some of packages are not able to import since i do not some files in my local envirenment. For example, from zipline.finance.performance import PerformanceTracker. the defult zipline 1.3.0 has no performance folder  in path\zipline\finance, it has no calendars folder in zipline\utils. As a result, I just revised the algorithm file by your description. it unable to show introday performance report.

**Comment by imkoukou** [comment]
@studyquant The file I posted are for a older version of Zipline. The Version 1.3.0 changed the folder structure, even the calendar has been separated as a single package folder outside the Zipline folder. I updated to Zipline 1.3.0 recently, and encountered the same problem at the first time, that 'minute_perf' not in perf.  For me, the problem was solved by:
1. The calendar is default initialized with get_calendar("NYSE") in file of "zipline\utils\run_algo.py", that not match my minute data well. I customized it, and specified the customized calendar for minute frequency data.
2. I found that initialization of TradingAlgorithm class in file of "zipline\utils\run_algo.py",the emission_rate is not correctly specified even if I used a command --data-frequency minute to tell zipline run with minute mode. I added the parameter of "emission_rate = data_frequency".
3. Also as older version, added my function of "_create_minute_stats" to return minute_stats.

Make sure you have registered a suitable calendar for your minute csv data, including the date in the calendar. 

That is all I've done for Zipline 1.3.0. And it can return the right minute data report to me.
[algorithm for Zipline Version 1.3.0.zip](https://github.com/quantopian/zipline/files/2310125/algorithm.for.Zipline.Version.1.3.0.zip)

**Comment by studyquant** [comment]
@imkoukou 
Sorry, I have replaced the file you uploaded, it still get some error.  Really appreciated your time and help.  I have uploaded my file and trading calender and data for you to test.   Thank you again for help. 


```
  File "C:\Anaconda3.5-64\lib\site-packages\zipline\algorithm.py", line 759, in run
    for perf in self.get_generator():
  File "C:\Anaconda3.5-64\lib\site-packages\zipline\algorithm.py", line 632, in get_generator
    return self._create_generator(self.sim_params)
  File "C:\Anaconda3.5-64\lib\site-packages\zipline\algorithm.py", line 607, in _create_generator
    metrics_tracker.handle_start_of_simulation(benchmark_source)
  File "C:\Anaconda3.5-64\lib\site-packages\zipline\finance\metrics\tracker.py", line 144, in handle_start_of_simulation
    benchmark_source,
  File "C:\Anaconda3.5-64\lib\site-packages\zipline\finance\metrics\tracker.py", line 127, in hook_implementation
    impl(*args, **kwargs)
  File "C:\Anaconda3.5-64\lib\site-packages\zipline\finance\metrics\metric.py", line 190, in start_of_simulation
    daily_returns_series = benchmark_source.daily_returns(
AttributeError: 'NoneType' object has no attribute 'daily_returns'

```
[zipline introday.zip](https://github.com/quantopian/zipline/files/2310756/zipline.introday.zip)

**Comment by HyperionSounds** [comment]
@imkoukou thanks for loading the strategy, i'm interested to take a look - are you currently using this live?

**Comment by dpkdeepakpandey** [comment]
@studyquant @imkoukou I am new to zipline and currently facing an issue while returning the minute performance.I have a dataset that consist of minute by minute data of 1 week but while running the algorithm(zipline.run_algorithm) i am getting performance(perf) on daily basis.I had made the changes which need to be done in run_algo.py and algorithm.py but still the performance(perf) is reflecting on the basis of daily performance.The data is entering into _create_minute_stats but while returning it is giving empty dataframe.

**Comment by balut91** [comment]
Hi @studyquant @imkoukou Updated the algorithm.py and run_algo.py still I am getting the daily results rather than minute result. Please update here if there is any work around.

**Comment by balut91** [comment]
@dpkdeepakpandey I found the solution.
In def _create_minute_stats(self, perfs):
    comment if (daytime in workDayStrList):

The workDayStrList is coming some random value which is not correct. Anyways the working days is already taken care when generating the perf results. I don't think we need to put that condition again to check working day list.
Please reply to this if this is correct/wrong.

**Comment by dpkdeepakpandey** [comment]
Yeah workDayStrList was coming with value [1111100] which i guess was equivalent to [Mon,Tue,Wed,Thu,Fri,Sat,Sun] but it was not helping.So,for the same i have given by default my_working_ days as [Mon,Tue,Wed,Thu,Fri] and later on we are comparing this with daytime and it works fine for minute level data.

Currently i am facing issues when i want to do the same with '5min','10min','15min'.Every time it is expecting data as minute by minute. Does zipline support for these minute integration also as i am not fully aware of it.

**Comment by balut91** [comment]
@dpkdeepakpandey Even I am looking a solution for the same. My strategy depends on different time frames like u said '5min' , '10min'.
I came across something called as batch_transform in zipline but looks like it is deprecated.
Please do a reply if you get any solution for this.

**Comment by balut91** [comment]
@dpkdeepakpandey 

Check out this link. It may help you
https://www.quantopian.com/posts/how-to-get-rsi-in-30-minutes-time-frame

**Comment by imkoukou** [comment]
@dpkdeepakpandey @balut91 
My solution to run at any period by:
1.  In utils/events.py 
 class EventManager(object)
change the handle_data() method to return a value. That will receive the value returned by handle() function in your running file.  For me, the handle_method is changed like this:
def handle_data(self, context, data, dt):
        # Revised by me: add return for handle_data
        rslts = []
        with self._create_context(data):
            for event in self._events:
                s = event.handle_data(
                    context,
                    data,
                    dt,
                )
                rslts.append(s)
        return rslts
2. In algorithm.py class TradingAlgorithm:
Change the handle_data() method to return the value returned by self._handle_data(self, data). After you finished step.1 the self._handle_data can return something.
3. In gens\tradesimulation.py class AlgorithmSimulator(object) 
def every_bar() in  def transform(): save the returned value like rrr = handle_data(algo, current_data, dt_to_use). (After you finished step.2 the handle_data() can return something).
Then in the transform(), you can find some like : 
elif action == MINUTE_END:
                    minute_msg = self._get_minute_message(
                        dt,
                        algo,
                        metrics_tracker,
                    )
                    yield minute_msg

Here, if rrr is None (you can define it) , just jump the yield by continue key word, for me it is:
                   if tmp_do:
                   # if True:
                        minute_msg = self._get_minute_message(
                            dt,
                            algo,
                            metrics_tracker,
                        )
                        yield minute_msg
                    else:
                        continue
4. Finally, you can jump some minutes by return with None at entry of  handle() function(you could also choose something else) in your running algorithm file. 

The period to process minute bar should be customized by the interval  when handle() return not None.
For example you can write to return 59 None + 1 not None to simulate 60minutes bar data.  
Besides, there is also some work you need to do: 
Compose new OHCL value for 60minute bar by using 60 1minute OHCL bars....

**Comment by dpkdeepakpandey** [comment]
@imkoukou 
Can you post those files where changes are required?

And what is the meaning of composing new OHCL value?Why is it required?

**Comment by dpkdeepakpandey** [comment]
@balut91 Did you got anything new when interval is of 5min,10min or 15min? I am not getting any help from the link which you have shared.

**Comment by tstevens02127** [comment]
Hello, I've been trying to run minute-level backtests with some issues but I've found your edits to the algorithm.py invaluable. I've got it to work now but my output has a strange quality. Even though I have minute level data:

2020-05-08 09:44:00+00:00
2020-05-08 09:45:00+00:00
2020-05-08 09:46:00+00:00

My output zeros out everything but the day, tossing the hour and minute detail out. So, for a given trading day, I've got a series of +400 lines of results that all share the same timestamp (that day's date). Is this an issue that you encountered? What part of this process could lead to this? Many thanks for your insight
Output:

2020-05-08   00:00:00+00:00
2020-05-08 00:00:00+00:00
2020-05-08 00:00:00+00:00

**Comment by tstevens02127** [comment]
@imkoukou You mentioned that you made changes to the benchmark, some of which I can see in the algorithm file you gave us. Would you mind sharing the other edits you made elsewhere in the zipline files? I'm tried to delete the whole thing but it's a mess. Thank for your insight

**Comment by AceFromSpace** [comment]
Hi I suppose I had solution for yours issue but for the newest version 1.4.1.

In the file zipline/finance/traiding.py, change default value of emission_rate to 'minute':
```
class SimulationParameters(object):
    def __init__(self,
                 start_session,
                 end_session,
                 trading_calendar,
                 capital_base=DEFAULT_CAPITAL_BASE,
                 emission_rate='minute',
                 data_frequency='daily',
                 arena='backtest'):
```
After that in zipline/algorith.py will be available  the 'minut_perf' in perfs like in the previous versions of zipline. So you just need to create function _create_minute_stats(self, perfs) and use it instead of _create_daily_stats(self, perfs), to parse data from simulation.

```
def _create_minute_stats(self, perfs):
        # create daily and cumulative stats dataframe
        minute_perfs = []
        # TODO: the loop here could overwrite expected properties
        # of daily_perf. Could potentially raise or log a
        # warning.
        for perf in perfs:
            if 'minute_perf' in perf:

                perf['minute_perf'].update(
                    perf['minute_perf'].pop('recorded_vars')
                )
                perf['minute_perf'].update(perf['cumulative_risk_metrics'])
                minute_perfs.append(perf['minute_perf'])
            else:
                self.risk_report = perf

        minute_dts = pd.DatetimeIndex(
            [p['period_close'] for p in minute_perfs], tz='UTC'
        )
        minute_stats = pd.DataFrame(minute_perfs, index=minute_dts)
        return minute_stats

```
That works for me. But let me know if there will be still any issues with that.  
[zipline_minute_perf_1_4_1.zip](https://github.com/quantopian/zipline/files/5721371/zipline_minute_perf_1_4_1.zip)

**Comment by tstevens02127** [comment]
Very good Ace! I have not updated to 1.4.1 but I was able to crowbar a solution for 1.3 (my setup). Can share if interested... and thanks for sharing yours.

**Comment by RiccaDS** [comment]
I confirm @AceFromSpace version works a charm for now. I am actually using zipline-reloaded. Thx
